In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv("../data/raw/nyc_311_2025_sample.csv")

In [45]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,status,borough,latitude,longitude
0,67351762,2025-12-31T23:59:28.000,2026-01-01T00:40:32.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10029.0,Closed,MANHATTAN,40.792141,-73.950097
1,67344624,2025-12-31T23:59:23.000,2026-01-01T01:03:42.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10031.0,Closed,MANHATTAN,40.825137,-73.949447
2,67346873,2025-12-31T23:59:21.000,2026-01-01T00:58:13.000,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11234.0,Closed,BROOKLYN,40.619995,-73.921167
3,67353004,2025-12-31T23:59:20.000,2026-01-01T00:57:31.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11235.0,Closed,BROOKLYN,40.591542,-73.955979
4,67350526,2025-12-31T23:59:12.000,2026-01-01T00:41:16.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10031.0,Closed,MANHATTAN,40.822593,-73.949525

In [46]:
# shape of the dataframe
df.shape

(50000, 13)

In [47]:
# general information of the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   unique_key      50000 non-null  int64
 1   created_date    50000 non-null  str
 2   closed_date     48854 non-null  str
 3   agency          50000 non-null  str
 4   agency_name     50000 non-null  str
 5   complaint_type  50000 non-null  str
 6   descriptor      49416 non-null  str
 7   location_type   44745 non-null  str
 8   incident_zip    49574 non-null  float64
 9   status          50000 non-null  str
 10  borough         50000 non-null  str
 11  latitude        49386 non-null  float64
 12  longitude       49386 non-null  float64
dtypes: float64(3), int64(1), str(9)
memory usage: 5.0 MB

In [48]:
# check for missing values
df.isnull().sum()

unique_key           0
created_date         0
closed_date       1146
agency               0
agency_name          0
complaint_type       0
descriptor         584
location_type     5255
incident_zip       426
status               0
borough              0
latitude           614
longitude          614
dtype: int64

In [49]:
# convert string type to datetime type
df["created_date"] = pd.to_datetime(df["created_date"])
df["closed_date"] = pd.to_datetime(df["closed_date"])

In [50]:
# Average resolution time
df["resolution_time"] = df["closed_date"] - df["created_date"]
df["resolution_hours"] = df["resolution_time"].dt.total_seconds() / 3600

In [51]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,status,borough,latitude,longitude,resolution_time,resolution_hours
0,67351762,2025-12-31 23:59:28,2026-01-01 00:40:32,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10029.0,Closed,MANHATTAN,40.792141,-73.950097,0 days 00:41:04,0.684444
1,67344624,2025-12-31 23:59:23,2026-01-01 01:03:42,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10031.0,Closed,MANHATTAN,40.825137,-73.949447,0 days 01:04:19,1.071944
2,67346873,2025-12-31 23:59:21,2026-01-01 00:58:13,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11234.0,Closed,BROOKLYN,40.619995,-73.921167,0 days 00:58:52,0.981111
3,67353004,2025-12-31 23:59:20,2026-01-01 00:57:31,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11235.0,Closed,BROOKLYN,40.591542,-73.955979,0 days 00:58:11,0.969722
4,67350526,2025-12-31 23:59:12,2026-01-01 00:41:16,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10031.0,Closed,MANHATTAN,40.822593,-73.949525,0 days 00:42:04,0.701111

In [52]:
df.to_csv(
    "../data/processed/nyc_311_clean.csv",
    index=False
)